#!/usr/bin/env bash
# First production deploy — idempotent, safe to re-run.
#
# Runs on a Hetzner VPS that has already been bootstrapped with
# ops/server-setup.sh (Docker, deploy user, UFW, directories). Does the
# full cold-start:
#
#   1. clone (or pull) the repo into $APP_DIR
#   2. generate a .env with random secrets if one doesn't exist
#   3. substitute ${DOMAIN} in the nginx site config
#   4. build prod images
#   5. start postgres, wait healthy, run alembic migrations
#   6. issue Let's Encrypt cert (init-letsencrypt.sh) on first run
#   7. start the full stack
#   8. smoke test + tail logs
#   9. install nightly pg_backup cron
#
# Usage (as the deploy user, not root):
#
#   REPO_URL=git@github.com:you/opportunity-radar.git \
#   DOMAIN=opportunityradar.com \
#   LETSENCRYPT_EMAIL=you@opportunityradar.com \
#   OPENAI_API_KEY=sk-... \
#   bash ~/first-deploy.sh
#
# Re-running is safe: repo pulls, secrets re-used, migrations are
# alembic's own no-op when up to date, cert skipped when already issued.

set -euo pipefail

# ---------------------------------------------------------------------
# Config (env vars, with explicit failure if required ones are missing)
# ---------------------------------------------------------------------
REPO_URL="${REPO_URL:?REPO_URL is required (git@... or https://...)}"
DOMAIN="${DOMAIN:?DOMAIN is required (e.g. opportunityradar.com)}"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:?LETSENCRYPT_EMAIL is required}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"

APP_DIR="${APP_DIR:-/opt/opportunity-radar}"
BACKUP_LOG="${BACKUP_LOG:-/var/log/or-backup.log}"
COMPOSE=(docker compose -f docker-compose.prod.yml)

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[1;31mXX\033[0m  %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------
# 0. Sanity
# ---------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker not found; run ops/server-setup.sh first"
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing"

# User must be able to talk to docker. If this fails, the deploy user
# was just added to the docker group but the shell still has the old
# group set — tell them to re-login.
docker ps >/dev/null 2>&1 || die "docker access denied; log out and back in (group 'docker' membership)"

command -v git >/dev/null 2>&1 || die "git not installed"
command -v openssl >/dev/null 2>&1 || die "openssl not installed"

# ---------------------------------------------------------------------
# 1. Repo: clone or pull
# ---------------------------------------------------------------------
if [[ -d "$APP_DIR/.git" ]]; then
    log "Repo exists at $APP_DIR — pulling latest"
    git -C "$APP_DIR" fetch --prune
    git -C "$APP_DIR" pull --ff-only
elif [[ -d "$APP_DIR" ]] && [[ -n "$(ls -A "$APP_DIR" 2>/dev/null)" ]]; then
    die "$APP_DIR exists and is not a git checkout — refusing to overwrite"
else
    log "Cloning $REPO_URL -> $APP_DIR"
    mkdir -p "$APP_DIR"
    git clone "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

[[ -f docker-compose.prod.yml ]] \
    || die "docker-compose.prod.yml not found in repo root — wrong branch?"

# ---------------------------------------------------------------------
# 2. .env — generate with random secrets if missing
# ---------------------------------------------------------------------
if [[ ! -f .env ]]; then
    log "Generating .env with random JWT_SECRET and POSTGRES_PASSWORD"

    # tr -dc limits to safe chars so we never smuggle / or $ into shell-
    # parsed env files.
    JWT_SECRET="$(openssl rand -base64 64 | tr -dc 'A-Za-z0-9' | cut -c1-64)"
    PG_PASSWORD="$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | cut -c1-32)"

    cat > .env <<EOF
# Generated by ops/first-deploy.sh on $(date -Iseconds)
# Edit by hand; re-running the deploy script will NOT overwrite.

DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# --- Postgres ---
POSTGRES_USER=opr
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=opportunity_radar

# --- Auth ---
JWT_SECRET=${JWT_SECRET}

# --- LLM ---
OPENAI_API_KEY=${OPENAI_API_KEY}
LLM_MODEL=gpt-4.1-mini

# --- Scheduler ---
SCHEDULER_ENABLED=true
PIPELINE_INTERVAL_MINUTES=60

# --- Trial ---
TRIAL_DAYS=7
EOF
    chmod 600 .env
else
    log ".env already present — keeping existing secrets"
fi

# Load .env into this shell so we can use $DOMAIN etc. below.
set -a; . ./.env; set +a

[[ -n "${OPENAI_API_KEY:-}" ]] \
    || warn "OPENAI_API_KEY is empty — LLM verification will short-circuit to is_signal=false"

# ---------------------------------------------------------------------
# 3. Nginx domain substitution (idempotent)
# ---------------------------------------------------------------------
NGINX_CONF="ops/nginx/conf.d/opportunity-radar.conf"
[[ -f "$NGINX_CONF" ]] || die "$NGINX_CONF missing"

if grep -q '\${DOMAIN}' "$NGINX_CONF"; then
    log "Substituting \${DOMAIN} -> ${DOMAIN} in $NGINX_CONF"
    sed -i "s/\${DOMAIN}/${DOMAIN}/g" "$NGINX_CONF"
elif grep -q "server_name ${DOMAIN}" "$NGINX_CONF"; then
    log "Nginx config already targets ${DOMAIN}"
else
    warn "Nginx config doesn't contain \${DOMAIN} nor server_name ${DOMAIN} —"
    warn "if you renamed the domain, edit $NGINX_CONF by hand."
fi

# ---------------------------------------------------------------------
# 4. Build images (uses build cache; first run is slow)
# ---------------------------------------------------------------------
log "Building images (first run: 3-5 min; subsequent runs: cached)"
"${COMPOSE[@]}" build --pull

# ---------------------------------------------------------------------
# 5. Start postgres, wait healthy, run migrations
# ---------------------------------------------------------------------
log "Starting postgres"
"${COMPOSE[@]}" up -d postgres

log "Waiting for postgres healthcheck"
for _ in $(seq 1 30); do
    status="$(docker inspect -f '{{.State.Health.Status}}' or_postgres 2>/dev/null || echo unknown)"
    [[ "$status" == "healthy" ]] && break
    sleep 2
done
[[ "$status" == "healthy" ]] || die "postgres did not become healthy in 60s"
log "postgres healthy"

log "Running alembic migrations"
"${COMPOSE[@]}" run --rm backend alembic upgrade head

# ---------------------------------------------------------------------
# 6. Let's Encrypt — bootstrap once, skip afterwards
# ---------------------------------------------------------------------
CERT_SENTINEL="$APP_DIR/.cert-issued-${DOMAIN}"
if [[ -f "$CERT_SENTINEL" ]]; then
    log "Cert already issued for ${DOMAIN} (sentinel: $CERT_SENTINEL)"
else
    log "Issuing Let's Encrypt cert for ${DOMAIN}"
    [[ -x ops/init-letsencrypt.sh ]] || chmod +x ops/init-letsencrypt.sh
    ./ops/init-letsencrypt.sh "$DOMAIN" "$LETSENCRYPT_EMAIL"
    touch "$CERT_SENTINEL"
fi

# ---------------------------------------------------------------------
# 7. Full stack up
# ---------------------------------------------------------------------
log "Starting full stack (backend, frontend, nginx, certbot)"
"${COMPOSE[@]}" up -d

# ---------------------------------------------------------------------
# 8. Smoke test + log preview
# ---------------------------------------------------------------------
log "Waiting 12s for services to settle"
sleep 12

log "Smoke test: https://${DOMAIN}/api/health"
if curl -fsS --max-time 10 "https://${DOMAIN}/api/health" >/dev/null; then
    log "✓ /api/health returned 200"
else
    warn "/api/health did not return 200 — inspect logs below"
fi

log "Recent logs per service (last 25 lines)"
for svc in postgres backend frontend nginx; do
    printf "\n\033[1;34m--- %s ---\033[0m\n" "$svc"
    "${COMPOSE[@]}" logs --tail 25 "$svc" 2>&1 || true
done

# ---------------------------------------------------------------------
# 9. Nightly backup cron (idempotent)
# ---------------------------------------------------------------------
if ! crontab -l 2>/dev/null | grep -q 'pg_backup.sh'; then
    log "Installing nightly backup cron (03:00 UTC)"
    [[ -x ops/backup/pg_backup.sh ]] || chmod +x ops/backup/pg_backup.sh
    ( crontab -l 2>/dev/null; \
      echo "0 3 * * * ${APP_DIR}/ops/backup/pg_backup.sh >> ${BACKUP_LOG} 2>&1" ) \
      | crontab -
else
    log "Backup cron already installed"
fi

# ---------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------
cat <<DONE

================================================================
  First deploy complete.
================================================================

  URL         : https://${DOMAIN}
  Health      : https://${DOMAIN}/api/health
  App dir     : ${APP_DIR}
  Status      : ${COMPOSE[*]} ps
  Logs        : ${COMPOSE[*]} logs -f <service>

  Seed a platform admin (optional, one-off):
    ${COMPOSE[*]} run --rm backend python -m scripts.seed_tenant \\
        --tenant-name "Admin Org" --tenant-slug admin \\
        --admin-email admin@${DOMAIN} --admin-password '<strong-pw>' \\
        --admin-full-name "Platform Admin"

  Re-deploy (after git changes):
    cd ${APP_DIR} && git pull && \\
    ${COMPOSE[*]} build && \\
    ${COMPOSE[*]} run --rm backend alembic upgrade head && \\
    ${COMPOSE[*]} up -d

================================================================

DONE
